---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amberleyway
  namespace: amberleyway
  labels:
    app: amberleyway
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: amberleyway
  template:
    metadata:
      labels:
        app: amberleyway
    spec:
      initContainers:
      - name: init
        image: alpine:3.10
        command:
        - sleep
        - "1"
      containers:
      - name: amberleyway
        image: johnlayton/amberleyway:0.0.11
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8092
          protocol: TCP
        - name: health
          containerPort: 8093
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8093
          initialDelaySeconds: 30
          failureThreshold: 1
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8093
          initialDelaySeconds: 30
          failureThreshold: 1
          periodSeconds: 5
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 64Mi
