apiVersion: v1
kind: Service
metadata:
  name: amberleyway
  namespace: amberleyway
  labels:
    app: amberleyway
spec:
  type: ClusterIP
  selector:
    app: amberleyway
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
